

#     Name: Krishna Sai Kottakota
#     Roll Number: CS20B044
#     Course: CS3205 Jan-May 2023 semester
#     Lab number: 2
#     Date of submission: 01/03/2023
#     I confirm that the source file is entirely written by me without
#     resorting to any dishonest means.

.SILENT : run clean 
run:
	python3 main.py $(portnum) $(file)

clean:
	rm *.output