# This is created by Krishna Sai Kottakota
# Roll No. CS20B044
# Date : 15/03/2023

.SILENT: run clean

run:
	javac lab3.java
	echo "lab3.class is created"
	echo "Give file names of input and ouputfiles"
	echo "Ex : java lab3 inputfile outputfile"
clean:
	rm *.class